name: VBA-Web
baseurl: "/VBA-Web"

url: http://vba-tools.github.io/VBA-Web/
github: https://github.com/VBA-tools/VBA-Web
download: https://github.com/VBA-tools/VBA-Web/releases
description: "Connect VBA, Excel, Access, and Office for Windows and Mac to web services and the web"
version: 4.0.20

defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: guides
    type: pages
  values:
    layout: guides
- scope:
    path: guides
    type: guides
  values:
    layout: guides
- scope:
    path: docs
    type: pages
  values:
    layout: docs

collections:
  guides:
    output: true
    permalink: /guides/:path/
    layout: guides

exclude:
- Gemfile
- Gemfile.lock
- readme.md

relative_permalinks: true
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
sass:
  style: :compressed
  sass_dir: _css