name: VBA-Web
baseurl: "/VBA-Web"

url: http://vba-tools.github.io
github: "https://github.com/VBA-tools/VBA-Web"
download: "https://github.com/VBA-tools/VBA-Web/releases"
description: "Connect VBA, Excel, Access, and Office for Windows and Mac to web services and the web"
version: 4.0.9

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: "guides"
    type: "pages"
  values:
    layout: "guides"
- scope:
    path: "docs"
    type: "pages"
  values:
    layout: "docs"

exclude:
- Gemfile
- Gemfile.lock
- readme.md

relative_permalinks: true
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
sass:
  style: :compressed
  sass_dir: _css